#!/usr/bin/env bash
# https://techexpert.tips/nginx/nginx-add-header/
# Adding Nginx server configuration so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html

# Configure redirection (301 Moved Permanently):
new_string="server_name _;\n\n\tlocation \/redirect_me {\n\t\t rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\t}"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default

# Nginx server configuration to have a custom 404 page containing the string Ceci n'est pas une page
sudo echo "Ceci n'est pas une page" > /var/www/html/page_404.html

new_string2="server_name _;\n\n\terror_page 404 \/page_404.html;\n\tlocation \/page_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sed -i "s/server_name _;/$new_string2/" /etc/nginx/sites-available/default

# Update Header - add_header
sudo sed -i "/listen 80 default_server/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-enabled/default
# restart the server so that the changes are applied

sudo service nginx restart
