#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install -y haproxy

# Backup del archivo original por si se rompe algo
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_backup.cfg

# Se configura el archivo haproxy.cfg para que maneje los dos servidores web (01 y 02)
echo "
frontend haproxy-main
    bind *:80
    option forwardfor
    default_backend nginx_servers
backend nginx_servers
    balance roundrobin
    server 4333-web-01  54.160.195.20:80 check
    server 4333-web-02  18.234.171.252:80 check
"| sudo tee -a /etc/haproxy/haproxy.cfg

# Restart haproxy load balancer
sudo service haproxy restart
