#!/usr/bin/env bash
# script that fixes this container so that Nginx runs as the nginx user
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i '/80 default_server/s/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
